// JsFromRoutes CacheKey 86fa1d4d4cbefc8ab4bca4e8c6cda7a5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/clients'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/clients'),
  new: /* #__PURE__ */ definePathHelper('get', '/api/clients/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/api/clients/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/clients/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/clients/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/clients/:id'),
}
