// JsFromRoutes CacheKey e27bf9e9b7cba1497cf842747ed6f587
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/gifs'),
}
