// JsFromRoutes CacheKey c17bc1a746480c1df8fde721e4b6d811
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/products'),
}
