// JsFromRoutes CacheKey 404f8a60d22cbcbe3664bde3cf44f04d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/products'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/products'),
  new: /* #__PURE__ */ definePathHelper('get', '/api/products/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/api/products/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/products/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/products/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/products/:id'),
}
