// JsFromRoutes CacheKey 68a54df6eed293e660a243b3d809c460
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/products'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/products'),
}
