services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: megaplex_development
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./tmp/redis:/data
    ports:
      - 6379:6379
