// JsFromRoutes CacheKey e9f1a2bef04c364b7f9a499f8f125e1a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/pages'),
}
